spring.application.name=personal

spring.ai.google.genai.api-key=${SPRING_AI_GOOGLE_GENAI_API_KEY}
spring.ai.google.genai.chat.options.model=${SPRING_AI_GOOGLE_GENAI_CHAT_OPTIONS_MODEL}

# Database connection
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialect (optional but good)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET}
spring.mail.host=
sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=${PORT:8080}